### ISSUE TITLE
gene naming in the simulated datasets from splatter 

### ISSUE THREAD

**Issue by qzhan321** [Oshlack/splatter#101]
Hi!

As many papers have recommended to use simulated datasets from splatter, I am trying to use it for my analysis as well! Kudos for your nice work!!

I am bench-marking a new batch effects correction method which utilizes a cell reference panel (primary cell lines from reliable bulk-seq studies). The idea is to calculate the correlation of expression profiles between cells in the single cell RNA-seq datasets and the cell lines in the reference panel to identify shared clusters among real datasets. I noticed that the genes in the simulated data from splatter did not correspond to the real gene names, but only named as "gene1" etc.

I understand for the majority of the batch effects, the pseudo-naming ("gene1" etc.) for the genes is enough. So my question is: is it possible to have simulated data (parameters estimated from real datasets) to have the same set of gene names as the those real datasets instead of "gene1" etc?

Thank you!

**Comment by lazappi** [comment]
Hi @qzhan321 

Thanks for giving **Splatter** a go! Because the genes are sampled from statistical distributions there is no direct link between the genes in the output from the `splat` simulation and the genes in your real data. You could rename them but I don't think that would solve your problem as they still wouldn't be related in any way.

You may be better off having a look at some of the other simulation models in **Splatter**. In particular the `zinbwave` and `lun2` simulations may give you what you want. They might also be models in other packages that maintain the gene relationship.

Some other alternatives could be to:

1. Create the data you need by manipulating a real dataset (i.e. adding noise in some way)
2. Instead of matching your simulations to your reference create a reference to match the simulations. For example make "pseudobulk" samples from simulated scRNA-seq to use as the reference when testing your algorithm.

Sorry I can't be more helpful. This is one of the drawbacks of a fully parametric model but often the extra flexibility you get is more useful.

**Comment by qzhan321** [comment]
Thanks for the helpful notes! Yeah, manipulating real datasets is a good way to simulate batch effects!
