### ISSUE TITLE
How to make the subgroup of cells more dense?

### ISSUE THREAD

**Issue by yuxiaokang-source** [Oshlack/splatter#112]
```
num_cells = c(100, 100)
group_prob = c(0.5, 0.5)

num_batches = length(num_cells)
num_clusters = length(group_prob)

params <- newSplatParams()
#params=setParam(params,"mean.shape",10)
simulated_data <- splatSimulate(batchCells = num_cells, group.prob = group_prob,
                                method = "groups", verbose = FALSE)
```
when i use tsne to plot the data, I get
![image](https://user-images.githubusercontent.com/59059267/111241067-57d78f00-8637-11eb-8aba-2db0e87edfd2.png)
![image](https://user-images.githubusercontent.com/59059267/111241080-5e660680-8637-11eb-900a-65978b4a40f5.png)

I want to make the groups  in the batch is more dense. the variation of groups is too large, what parameters should I change If I don't want to increase the number of cells?

**Comment by lazappi** [comment]
Hi @yuxiaokang-source 

Thanks for giving **{splatter}** a go! Can you please explain what you mean by "more dense"? Are you looking for bigger/smaller differences between batches/groups?

**Comment by yuxiaokang-source** [comment]
Sorry about that , for example, I want the the variance of group in each batch will be more small ,so the point in group(group1 of batch1) will be more near to each other.

**Comment by lazappi** [comment]
Thanks for the clarification. There isn't really a way to adjust parameters for a specific group + batch combination with the current Splat interface. You can adjust the batch effect parameters which will make the two batches more/less similar or the DE parameters which will make the groups more/less similar but not for a specific group + batch.This is something that is a known issue which I'm planning to address in an improved interface (when I can find the time).

Now that I think about I'm not sure that there is a way to consider adjusting variability for a group at all so that's something else to consider.

**Comment by lazappi** [comment]
@yuxiaokang-source I'm going to close this issue but feel free to comment if you have further questions.
