### ISSUE TITLE
Dynamic path.nSteps? Feature request

### ISSUE THREAD

**Issue by alexandruioanvoda** [Oshlack/splatter#124]
Is there a plan to add a variable number of path.nSteps? So that differentiation paths can be both discrete and continuous inside the same dataset?

This is a great package, thank you for creating & maintaining it!

**Comment by lazappi** [comment]
Hi @alexandruioanvoda 

Do you have any more detail on what you would like to see? If not I will probably close this.

**Comment by alexandruioanvoda** [comment]
Hi!

By that I meant a version of the `path.nSteps` param where you can pass a vector of numbers-of-steps.
e.g. if you did `path.nSteps = c(1, 50)`,  then the differentiation between group 1 and group 2 would be binary (very separate clusters) whereas between group 2 and 3 it would be a smooth 50-steps differentiation path. Does that make sense? I can provide an example cartoon PCA tomorrow if needed?

Thank you very much for taking the time to check this! ^_^

**Comment by lazappi** [comment]
I think this should already be possible (but I think you need to set `path.skew` rather than `path.nSteps`). Have a look at this example:

```r
sce <- splatSimulatePaths(
	nGenes = 10000,
	batchCells = 600,
	de.prob = 0.2,
	de.facLoc = 0.2,
	group.prob = c(0.25, 0.25, 0.25, 0.25),
	path.nSteps = c(50, 50, 1, 1),
	path.skew = c(0.5, 0.01, 0.5, 0.01)
)

sce <- scuttle::logNormCounts(sce)
hvgs <- scran::getTopHVGs(sce)
sce <- scran::fixedPCA(sce, subset.row = hvgs)
sce <- scater::runUMAP(sce, dimred = "PCA")
scater::plotUMAP(sce, colour_by = "Group")
```

![paths](https://user-images.githubusercontent.com/6869320/149088962-6db0b863-7555-4f0b-9214-77d5ad460c62.png)

Here we have four paths with the same number of cells but different combinations of `nSteps` and `skew` (Note there seems to be a bug when `path.skew = 0` so I have used a small value here):

* Path 1 - `nSteps = 50`, `skew = 0.5`
* Path 2 - `nSteps = 50`, `skew = 0.01`
* Path 3 - `nSteps = 1`, `skew = 0.5`
* Path 4 - `nSteps = 1`, `skew = 0.01`

Path 1 is roughly the default, Path 2 is a separate cluster away from the origin (which I think is what you want), Path 3 and Path 4 are both around the origin regardless of the `skew` because there is only one step.

Does that make sense? `path.nSteps` controls the distance of the end point from the starting point and `path.skew` controls how cells are distributed along that path. Both of these can be set individually for each path by supplying a vector.

**Comment by alexandruioanvoda** [comment]
Really cool, thank you very much for the explanation!
