### ISSUE TITLE
Problem with splatEstimate() when using a particular dataset

### ISSUE THREAD

**Issue by Felitsiya** [Oshlack/splatter#133]
Hello!

I get an error when running splatEstimate() on a data set (that is actually generated).

cnts <- read.table("mcmcparams1_trn_mod.txt", skip = 1, sep = ",")
cnts <- t(cnts)

library(splatter)

splat_name <- "TAMU1_splat_set.txt"
genes <- nrow(cnts)
samples <- ncol(cnts)
ndiff<- 0.05

params <- splatEstimate(cnts)

Error in qr.solve(QR.B, cc) : singular matrix 'a' in solve
In addition: Warning message:
In value[[3L]](cond) :
  Fitting dropout using the Gauss-Newton method failed, using the Golub-Pereyra algorithm instead

Here is a link to the data set I am using:

https://drive.google.com/drive/folders/1yVHKpm5FNjGcIzvJitJm_4_LFb8rH0HP?usp=sharing

Thank you in advance.

Sincerely,
Felitsiya Shakola

**Comment by lazappi** [comment]
Hi @Felitsiya

Thanks for giving **{splatter}** a go! The provided dataset was very helpful and I was able to reproduce the error. The part that is failing is fitting the relationship between mean expression and proportion of zeros. I think in this case it is because your generated data doesn't look a lot like real scRNA-seq, for example there are no zero counts in the provided matrix. This is still something we should handle better though.

**Comment by lazappi** [comment]
This should now work without an error in the development version.
