### ISSUE TITLE
How to set de.prob to get a specific number (or estimation) of DE genes per cluster? 

### ISSUE THREAD

**Issue by emkahuda** [Oshlack/splatter#135]
This Splatter software is really useful to generate synthetic data. I am thinking to create a synthetic data with a specific scenario like this. Let say we have 20,000 genes, and we want to have 10 clusters 1) with the same size,  and 2) with different size. If I want to have more possible scenarios, such as a lot of DE genes, quite a lot of DE genes, and small number of DE genes, we can set de.prob to obtain them. My question is that if I want to get 1) around 500 DE gene in the first scenario (all cluster has the same size) and 2) around 500 DE gene in the first scenario (all cluster has the same size), how to calculate this by setting the de.prob? For example, group.prob = c(0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08), de.prob = c(0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625). Does it mean the estimated number of DE gene for each cluster will be 0.08×20,000×0.0625 = 100 so in total there will be 1000 DE genes? Could you please explain about it? I want to see the results if we set the data to have three different number of DE genes for each scenario (such as 500 DE genes, 250 DE genes, and 50 DE genes). Thank you very much.

**Comment by lazappi** [comment]
Hi @emkahuda 

Thanks for giving **{splatter}** a go! I will briefly explain these parameters but I suggest you have a look at the [parameters vignette](https://bioconductor.org/packages/release/bioc/vignettes/splatter/inst/doc/splat_params.html) to get a better idea of what they all do.

* `group.prob` - Controls the probability that each cell is assigned to each cluster. The length of the vector controls the number of groups and the values control the relative sizes.
* `de.prob` - Controls the probability that each gene is DE in each group. It can be either a single value used for every group or a vector the same length as `group.prob` with different values for each group (so if there are four clusters then `de.prob = 0.1` is equivalent to `de.prob = c(0.1, 0.1, 0.1, 0.1)`).
* `de.facLoc`/`de.facScale` - These control the foldchange for the selected DE genes. Together with `de.prob` they affect how different two clusters are from each other.

The expected number of DE genes for one group is `nGenes * de.prob`. So if you had 20000 genes and `de.prob = 0.1` the expected number of DE genes is 2000. **Note that this is only an expected number**. This is because the DE genes for each group are not mutually exclusive. For example, if we had two groups and `de.prob = 0.5` we wouldn't get all genes being DE (half for one group and half in the other), instead we would get ~75% DE (~25% in one group, ~25% in the other and ~25% in both). Because this is all done probabilistically controlling the exact number of DE genes is difficult.

Hope that helps
