### ISSUE TITLE
Changing the number of samples with splatPop

### ISSUE THREAD

**Issue by LeonHafner** [Oshlack/splatter#138]
Hello together,
Is there any way to change the default value of 5 samples in a splatPop simulation?
I have tried all the parameters listed in the supplements of the paper, however, I could not change the number of samples.
Thanks!

**Comment by lazappi** [comment]
Hi @LeonHafner 

Thanks for giving **{splatter}** and `splatPop` a go 🎉! Please have a look at the [`splatPop` vignette](https://bioconductor.org/packages/release/bioc/vignettes/splatter/inst/doc/splatPop.html). If that doesn't answer your question @azodichr should be able to help you out.

(P.S. It is usually better to open a new issue rather than changing the title to something completely different, that can get a bit confusing.)

**Comment by azodichr** [comment]
Hello @LeonHafner, splatPop will simulate cells for each individual in the vcf you provide. If you are using the mockVCF function you can change the number of samples with the n.samples parameter: 

```
vcf <- mockVCF(n.samples = 10)
```

**Comment by LeonHafner** [comment]
Thanks, that explains it to me!
