### ISSUE TITLE
SplatPop DE genes within groups and condition

### ISSUE THREAD

**Issue by LeonHafner** [Oshlack/splatter#140]
Hi
I have seen issue #57 and how the genes are DE in a splatter simulation.
For the updated splatpop model, the same can be applied as desribed there, correct?
Instead of DEFacGroup1 the column is called GroupDE.Group1 here?
Can I assume the same for Conditions with ConditionDE.Condition1, so the gene is not DE if ConditionDE.Condition1 and ConditionDE.Condition2 are 1 and DE otherwise?
How comes that I end up with 5102 DE genes out of 10k genes, if my cde.prob = 0.3? Is this still inside the variance?

**Comment by azodichr** [comment]
Hi @LeonHafner, 
Yes, the DE approach used in splatter is the same as what is implemented in splatPop, so DEFacGroup1 and GroupDE.Group1 are telling you the same information for splatter and splatPop, respectively (@lazappi I can update these column names from splatPop to be consistent with splatter). 

Regarding the number of conditionally DE genes you are getting, the `cde.prob` parameter controls the probability that a gene will be DE in any **one** condition. To achieve about 30% of genes with conditional DE across a whole simulated population, if you are simulating 2 conditions you need to set `cde.prob = 0.15`, if you are simulating 3 conditions `cde.prob = 0.1`, etc. Because splatPop randomly selects genes to be DE for each condition separately, some genes might be assigned a DE factor for both conditions. Thus, the "global" DE across all conditions will likely be a bit below 30% if the above cde.prob values are used.
