### ISSUE TITLE
Alternative gamma or nbinom parameterization in Splat

### ISSUE THREAD

**Issue by gokceneraslan** [Oshlack/splatter#15]
Thanks for the cool method and implementation! Does it make sense to provide alternative parameterization for the mean gamma distribution to make it more intuitive for users? For example, as an alternative to shape and rate, people can also specify just gamma mean and variance, or alternatively, negative binomial mean and dispersion (which should correspond to gamma `shape/rate` and `shape`, respectively.) I think, it'd be easier to be able to set the mean expression to a specific value, which is 2 now by default (`0.6/0.3`), right?

**Comment by lazappi** [comment]
Hi

Thanks for you interest in Splatter.

The parameterisation we have used for the mean gamma distribution is the one that is most commonly used in the field (shape and rate). There is an alternative parameterisation (shape and scale) but that isn't used as often. As far as I am aware it isn't possible to parameterise a gamma using mean and variance directly but (without doing the maths) I guess it would be possible to have the user specify mean/variance and convert them to shape/rate. I don't think that would be a standard thing to do though so I am reluctant to support it.

In our model the gamma is used to generate a different mean for each gene. You could have the user specify mean and dispersion for the NB directly but they would need to do it for every gene (or they would all look the same). I have had some thoughts about how this kind of simulation might work but haven't tried to implement it.

For the Splat simulation we can tried to come up with a good estimation procedure so that the user shouldn't have to set these parameters directly as it can be a bit hard to tell what reasonable values are.

I hope that helps. I am going to close this issue but feel free to continue commenting if you want to discuss it further.

Luke
