### ISSUE TITLE
How to simulate marker genes

### ISSUE THREAD

**Issue by VivLon** [Oshlack/splatter#162]
Hi, thank you for creating the splatter package and it's great! 

However, I'm having questions with simulating significant marker genes. I have already simulated a 7-group dataset. Right now, my task is to assign 5 markers to each group. Which parameter can I tune to achieve this? I've read through the previous issues, and I saw you talking about changing de.facLoc and de.facScale, are there any suggestions with how to tune those parameters?

What's more, when I'm simulating more than 7 groups, and then I draw the umap with scanpy, I usually find out that the groups are not very separated. Are there any parameters to change this?
![image](https://user-images.githubusercontent.com/88369024/228513353-0b1789a0-7328-42d2-afd9-9be688fffabc.png)

**Comment by lazappi** [comment]
Hi @VivLon, thanks for giving **{splatter}** a go! Can you please explain a bit more what you are trying to achieve and share the code you are using currently? I'm not quite sure what to suggest at the moment.

**Comment by VivLon** [comment]
Thank you for your reply! I've already solved the second problem. Different groups are not separated in umap is just because I didn't update my scanpy. 

But the first problem still exists. My task is to give each group the same number of marker genes, and make the markers as significant as possible. But the problem is, if I set a threshold of p-value and LFC, how to make the number of markers the same in every group? Do you have any suggestions?

**Comment by lazappi** [comment]
Differential expression is controlled by the `de.prob`, `de.facLoc` and `de.facScale` parameters. `de.prob` controls the probability a gene is DE in that cell group, and `de.facLoc` and `de.facScale` control the distribution that fold changes for DE genes are sampled. See the [parameters vignette](https://bioconductor.org/packages/release/bioc/vignettes/splatter/inst/doc/splat_params.html) for more details.

Because the simulation is probabilistic it is difficult to define exactly how many DE genes each group has (and this is further complicated when there are more than two groups). If you really want that you that you might consider subsetting to only genes that match your criteria. I would suggest thinking about what you want to test with this scenario though, it seems quite unrealistic for there to be the same number of markers per group and for those to be very significantly different.

**Comment by VivLon** [comment]
It's alright, we finally chose to select first x genes in a Wilcoxon rank-sum test as markers. Is there any suggestions on how to make genes in different groups more significantly different?

**Comment by lazappi** [comment]
`de.facLoc` and `de.facScale` control how different the DE genes are between groups. You can see that demonstrated in the vignette I linked to above.

**Comment by lazappi** [comment]
@VivLon Do you have any follow up questions or can I close this issue?

**Comment by VivLon** [comment]
Sure, I don't have any further questions and you can close this now. Thank you very much for your previous explanations.-------- 原始邮件 --------发件人： Luke Zappia ***@***.***>日期： 2023年6月2日周五 下午3:49收件人： Oshlack/splatter ***@***.***>抄送： VivLon ***@***.***>, Mention ***@***.***>主    题： Re: [Oshlack/splatter] How to simulate marker genes (Issue #162)
@VivLon Do you have any follow up questions or can I close this issue?
