### ISSUE TITLE
How to generate genes with fixed distributions?

### ISSUE THREAD

**Issue by wanlinjuan** [Oshlack/splatter#164]
I wonder how to generate genes with fixed distributions. I tried to use the same parameters and different seed, but the gene means are very different. For example,

sce <- mockSCE()

params <- splatEstimate(sce)

data1 = splatSimulate(params,seed=1)
plot(rowMeans(counts(data1)))

data2 = splatSimulate(params,seed=2)
plot(rowMeans(counts(data2)))

plot(rowMeans(counts(data1)) - rowMeans(counts(data2)))
![image](https://github.com/Oshlack/splatter/assets/25786875/37de950b-3194-4669-983a-618f316c358a)

I would like to see the difference of gene means to be centered around 0 with small variations.

Thank you so much!

**Comment by lazappi** [comment]
Hi @wanlinjuan 

I'm not entirely sure what your question is so please ask for more information if needed but I will try to answer. Two Splat simulations are completely independent of each other. That means that Gene 1 in one simulation has no relationship to Gene 1 in a second simulation. Unfortunately, that two separate simulations can't be compared in any way. Depending on the exact scenario you want to simulate there may be a work around for this but I would need more information to suggest something.

**Comment by wanlinjuan** [comment]
> 

Hi @lazappi! I think you already answer my question. Thank you so much. 

Besides, from the [scDesign2 paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02367-2/tables/1), I've seen Lun2 model has gene preservation. Does it mean two Lun2 simulations are dependent? 

Thank you so much!

**Comment by lazappi** [comment]
It's been a while since I looked closely at the Lun2 model but I think the genes can be consistent between simulations. This is only true when the number of genes to simulate is the same as the number in the dataset that parameters were estimated from (you will receive a warning in this case). While the genes may match between two simulations with this model things like which genes are selected to be differentially expressed are still random so there will still be differences between them. If this is important to your use case I would double check it before using this model.

**Comment by lazappi** [comment]
Closing this issue, please reopen if needed.
