### ISSUE TITLE
More control over the generation of DE genes

### ISSUE THREAD

**Issue by farcasia** [Oshlack/splatter#21]
Hi,

I was wondering whether the following scenario can be simulated with splat. I want to generate 4 scRNA-seq data samples, where two of the samples are from the same patient (let's call them P1C and P1D), and the other two are from another patient (let's call them P2C and P2D). In each pair of samples, I want to create DE genes in PxD compared to PxC (where x stands for 1 or 2). I also want the same set of genes to be down or up regulated in PxD compared to PxC. Now, I see that you can create groups and set the DE probability per group using splat. But in comparison to what are genes in the group differentially expressed? In regard to the batch? Do you plan to add functionality to control the set of genes one wants to generate as DE (or you can already do that, and I missed it)?

Thank you!

**Comment by farcasia** [comment]
Moreover, how do batches and groups interact? I see that if you create 2 batches and 4 groups, the 4 groups are present in all 2 batches (I was expecting that you could set the groups per batch). Is this a feature or a bug?

By the way, thank you for creating this package :).

**Comment by lazappi** [comment]
Hi

Thanks for giving Splatter a go, I hope it can be useful for what you are working on.

The way batches and groups work at the moment I think of a "batch" as a sample of the tissue etc. of interest and a "group" as a kind of cell in that sample. So imagine you were studying the heart and had three samples of cardiac tissue (batches), you would expect to see technical differences between them, but you would expect to see the same cell types (groups) in each sample. This is why all of the groups appear in each batch.

Because of the way things are set up I am not sure it is currently possible to simulate the scenario you describe above. If I am understanding you correctly you want to have a relationship between batch and group? So instead of getting all combinations (Patient 1 Sample 1, P1S2, P1S3, P1S4, P2S1, P2S2, P2S3, P2S4) you want to just have separate batches for each patient (P1S1, P1S2, P2S3, P2S4). Splatter can't simulate that at the moment, but I have had a couple of similar questions so it might be something we can add in the next release (if time permits). For now my suggestion would be to simulate a dataset with two groups and four batches then filter the cells so you are left with the group x batch (patient x sample) combinations that you want.

As for simulating DE. Differential expression is conducted at the level of groups. Batches are meant to represent purely technical variance. All DE is calculated relative to a fictional base cell so you should see DE between any two groups. I have some ideas about how this could be done a bit better, but again it depends on time if they will be implemented by the next release. Controlling which genes are DE could be part of that. 

Sorry for all the information, I hope that makes things a bit clearer. Let me know if you have any other questions or ideas for things you would like to be able to do, I want Splatter to be useful for as many people as possible.

**Comment by farcasia** [comment]
Hi Luke,

Thank you for the quick reply. I imagined this was the behavior of
splatter, but I just wanted to make sure.

Best,
Ana.

**Comment by lazappi** [comment]
Hi @farcasia 

I'm going to close this issue. Feel free to comment if you are still interested in this or open another issue if you want to ask something else.
