### ISSUE TITLE
Is there way to specify the genes undergoing DE?

### ISSUE THREAD

**Issue by lynnyi** [Oshlack/splatter#45]
Hi,

I'm curious whether one can use Splatter to simulate DE on specific genes. Based on my understanding from reading the paragraph about simulating groups in your paper ("Additionally, parameters controlling the probability that genes are differentially expressed as well as the magnitude and direction of DE factors can be set individually for each group."), one can specify the probability that genes can be DE. But what about a specific gene being DE with probability 1 and other genes being DE with probability 0 -- is that possible with the current implementation of Splatter?

Thanks,
Lynn

**Comment by lazappi** [comment]
Hi @lynnyi 

Thanks for giving Splatter a go!

I think you are understanding things correctly. At the moment it's possible to set the DE parameters for the Splat simulation at the group level so that different groups can have different amounts (more/less DE genes) or different magnitudes (bigger/smaller fold changes), but this can't be done for individual genes. It should be possible to implement it at the gene level but it would be a bit tricky because if there are multiple groups you would need gene x group matrices of the parameters. 

Can you maybe tell me a bit more about what you are trying to simulate? I might have some ideas of alternative ways to do it, or maybe can suggest one of the other simulations.

**Comment by lynnyi** [comment]
Hi Luke, thanks for the response. I am trying to simulate DE genes with isoform-specific effect sizes. Because there is no concept of transcripts/genes in the Splatter framework, I was hoping to specify by name the transcripts to be perturbed.  What would you suggest as an alternative?
Thanks,
Lynn

**Comment by chenxofhit** [comment]
Hi  @lazappi , I would like to simulate a dataset with two distinct groups of cells, and with the desired amount of DE genes. In this case can I use splatter to go ahead, I just wanna test a method if it is sensitive with increasing numbers of DE genes. My question is a little like that of lynnyi.

**Comment by lazappi** [comment]
Hi @chenxofhit. Thanks for your interest in Splatter. Your question seems to be mostly about how to use Splatter so it is more appropriate for the Bioconductor forum https://support.bioconductor.org/. Can you please open a new question there with more details about what you would like to do?

**Comment by chenxofhit** [comment]
@lazappi Sorry for the late reply, and I have posted a question as you desired there: https://support.bioconductor.org/p/117702/. If any question, please let me know.
Thank you very much!

**Comment by lazappi** [comment]
Closing this for now.
