### ISSUE TITLE
dropout turned off by default in splatSimulate?

### ISSUE THREAD

**Issue by brianjohnhaas** [Oshlack/splatter#61]
Hi Luke,

It looks like the default dropout mode setting for splat estimate parameters is set to 'none'.  I needed to use setParams(params, dropout.type='experiment') in order to include the dropout simulation.   Would it be best to have 'experiment' be the default rather than 'none', since dropout is a major component of single cell data?

Also, it looks like this part of the code may have been reworked from the paper version, as the 
splatter-paper/R/simulate_datasets.R included 

```
splatter::splatSimulate(params,
                                        dropout.present = FALSE, 
...
```

as a way of turning the dropout on/off, and that doesn't appear to be the case w/ the current code.

I have a number of what are probably naive questions about some of the math....  Would it be ok if I emailed you directly, or would you prefer that I use this or the bioc forum?  

many thanks!!

~brian

**Comment by lazappi** [comment]
Hi Brian

Thanks for giving Splatter a go. We turn the additional dropout off by default because we find it isn't necessary for reproducing many datasets as the low means produce enough zeros, particularly for UMI datasets such as those from the 10x Chromium. 

You are correct about changes to the dropout arguments, replacing `dropout.present` with `dropout.type`. This happened in v1.3.5 after a request to allow different levels of dropout for different cells (see #25). Setting `dropout.type` to `"none"/"experiment"` should be equivalent to setting the old `dropout.present` to `FALSE/TRUE`.

Happy for you to email if you have a list of things to ask, particularly if they are more about the theory than the software.

Luke

**Comment by bhaasIMM** [comment]
Thanks, Luke!    I'll email you later in the week w/ my theory questions.  Thx again, and happy new year!
